### PR TITLE
[NK] Added contract test for get-help-ticket and feedback deskpro end…

### PR DESCRIPTION
**Pull request by ngoulongkam**
…point

### CODE REVIEW

**Comment by howzat** [comment]
My preference would be to use the auth client library (declaring it as a dependency) than copying this code around. I think we should revisit the reasons this pattern exists once @frankoid is back, perhaps we can avoid having to do this now.

**Comment by frankoid** [comment]
@howzat this code is POSTing to auth-login-api to create a new auth session (and get a bearer token that can subsequently be sent in the Authorization header to endpoints that require a logged in user).

Does the auth client library support this? I think it probably doesn't, the auth-client library is targeted towards allowing services to check properties of the current logged in user rather than logging users in.

**Comment by frankoid** [comment]
@howzat this code is POSTing to auth-login-api to create a new auth session (and get a bearer token that can subsequently be sent in the Authorization header to endpoints that require a logged in user).

Does the auth client library support this? I'm not sure it does, the auth-client library seems to be intended to allow services to check properties of the current logged in user rather than to allow services to log users in.

**Comment by frankoid** [comment]
Further to our discussions just now it looks like there is actually already a library for calling auth-login-api that we could use if we wanted to: https://github.com/hmrc/auth-test

**Pull request merged**
